name: portfolio_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  sliding_sheet: ^0.5.2
  font_awesome_flutter: ^10.1.0
  url_launcher: ^6.1.10
  community_material_icon: ^5.9.55


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
     - assets/
